config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'boards#index'
  
  resources :boards do
    resources :tasks, only: [:new, :create, :show, :edit, :update, :destroy] do
      resources :comments, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id          :bigint           not null, primary key
#  description :text             not null
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :name, presence:true, length: { minimum: 2 }
  
  
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  task_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_comments_on_task_id  (task_id)
#  index_comments_on_user_id  (user_id)
#
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task
  validates :content, presence: true
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  limit      :datetime
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#
class Task < ApplicationRecord
  
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :board
  has_many :comments, dependent: :destroy
  
  has_one_attached :eyecatch
  
  def eyecatch_image
    if self.eyecatch.present?
      self.eyecatch
    else
      'saikoro.png'
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  
  
  def user_account
    self.email.split('@').first
  end
  
  def has_written?(board)
    self.boards.exists?(id: board.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :delete]
  
  
  def index
    @boards = Board.all
  end
  
  def new
    @board = current_user.boards.build
  end
  
  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to boards_path, notice: '保存しました'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end
  
  def show
    @board = Board.find(params[:id])
    @tasks = @board.tasks
  end
  
  def edit
    @board = current_user.boards.find(params[:id])
  end
  
  def update
    @board = current_user.boards.find(params[:id])
    if @board.update(board_params)
      redirect_to board_path(@board), notice: '更新しました'
    else
      flash.now[:error] = '更新に失敗しました'
      render :edit
    end
  end
  
  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy!
    redirect_to root_path, notice: '削除しました'
  end
  
  
  private
  
  def board_params
    params.require(:board).permit(:user_id, :name, :description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
    task = Task.find(params[:task_id])
    @comment = task.comments.build
  end
  
  def create
    task = Task.find(params[:task_id])
    @comment = task.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to board_task_path(task.board_id, task.id), notice: 'コメントを作成しました'
    else
      flash.now[:error] = 'コメントを追加できませんでした'
      render :new
    end
  end
  
  
  
  
  private
  
    def comment_params
      params.require(:comment).permit(:user_id, :content, :task_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def new
    board = Board.find(params[:board_id])
    @task = board.tasks.build
  end
  
  def create
    board = Board.find(params[:board_id])
    @task = board.tasks.build(task_params)
    if @task.save
      redirect_to board_path(@task.board_id), notice: 'タスクを追加しました'
    else
      flash.now[:error] = 'タスクの追加に失敗しました'
      render :new
    end
  end
  
  def show
    board = Board.find(params[:board_id])
    @task = board.tasks.find(params[:id])
    @comments = @task.comments
  end
  
  def edit
    board = Board.find(params[:board_id])
    @task = board.tasks.find(params[:id])
  end
  
  def update
    board = Board.find(params[:board_id])
    @task = board.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to board_task_path, notice: 'タスクを更新しました'
    else
      flash.now[:error] = 'タスクを更新できませんでした'
      render :edit
    end
  end
  
  def destroy
    board = Board.find(params[:board_id])
    task = board.tasks.find(params[:id])
    task.destroy!
    redirect_to board_path(board), notice: 'タスクを削除しました'
  end
  
  
  private
  
    def task_params
      params.require(:task).permit(:title, :content, :limit, :eyecatch)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/edit.html.haml
.container
  - @board.errors.full_messages.each do |message|
    %ul
      %li= message
  %h1 Edit Board
  = form_with(model: @board, url: board_path(@board.id), local: true, method: 'patch') do |f|
    %div
      = f.label :name, 'Name'
    %div
      = f.text_field :name
    %div
      = f.label :description, 'Description'
    %div
      = f.text_area :description, class: 'textarea'
    %div
      = f.submit 'Submit', class: 'btn-primary'

app/views/boards/index.html.haml
.container
  %h1 All Boards
  - @boards.each do |board|
    = link_to board_path(board) do
      .card
        .card_title
          %p= board.name
        .card_content
          %p= board.user.user_account
  .card.new
    = link_to '+Add new board', new_board_path

app/views/boards/new.html.haml
.container
  - @board.errors.full_messages.each do |message|
    %ul
      %li= message
  %h1 New Board
  = form_with(model: @board, url: boards_path, local: true, method: 'post') do |f|
    %div
      = f.label :name, 'Name'
    %div
      = f.text_field :name
    %div
      = f.label :description, 'Description'
    %div
      = f.text_area :description, class: 'textarea'
    %div
      = f.submit 'Submit', class: 'btn-primary'

app/views/boards/show.html.haml
.container
  .board
    .board_title
      %h1= @board.name
    .board_content
      %p= @board.description
    - if user_signed_in? && current_user.has_written?(@board)
      .board_select
        %p= link_to 'edit', edit_board_path(@board.id)
        %p= link_to 'delete', board_path, local: true, data: { method: 'delete', confirm: '本当に削除しますか？'}
  .task
    - @tasks.each do |task|
      = link_to board_task_path(@board,task) do
        .task_field
          = image_tag task.eyecatch_image
          %h2= task.title
          %p= task.content
    .task_add
      %p= link_to 'Add tasks', new_board_task_path(@board), class: 'btn-secondary'

app/views/comments/new.html.haml
.container
  - @comment.errors.full_messages.each do |message|
    %ul
      %li= message
  %h1 New Comment
  = form_with(model: @comment, url: board_task_comments_path(@comment.task.board_id,@comment.task_id), local: true, method: 'post') do |f|
    %div
      = f.text_field :content
    %div
      = f.submit 'Submit', class: 'btn-primary'

app/views/home/index.html.haml
%h1 Home

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TodoApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  %body
    %header.header
      .header_contents
        .header_contents_title
          = link_to root_path do
            %h2 Boards
        .header_contents_menu
          - if user_signed_in?
            %ul
              %li= link_to 'Log out', destroy_user_session_path, data: { method: 'delete'}
          - else
            %ul
              %li= link_to 'Sign up', new_user_registration_path
              %li= link_to 'Sign in', new_user_session_path
    - if flash.present?
      - flash.each do | key, value |
        %p{:class => "\#{key}"}= value
    = yield

app/views/tasks/edit.html.haml
.container
  - @task.errors.full_messages.each do |message|
    %ul
      %li= message
  %h1 Edit Task
  = form_with(model: @task, url: board_task_path(@task.board_id,@task.id), local: true, method: 'patch') do |f|
    %div
      = f.label :eyecatch, 'Eyecatch'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'Title'
    %div
      = f.text_field :title
    %div
      = f.label :content, 'Content'
    %div
      = f.text_area :content, class: 'textarea'
    %div
      = f.label :limit, 'Limit'
    %div
      = f.date_field :limit
    %div
      = f.submit 'Submit', class: 'btn-secondary'

app/views/tasks/new.html.haml
.container
  - @task.errors.full_messages.each do |message|
    %ul
      %li= message
  %h1 New Task
  = form_with(model: @task, url: board_tasks_path(@task.board_id), local: true, method: 'post') do |f|
    %div
      = f.label :eyecatch, 'Eyecatch'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'Title'
    %div
      = f.text_field :title
    %div
      = f.label :content, 'Content'
    %div
      = f.text_area :content, class: 'textarea'
    %div
      = f.label :limit, 'Limit'
    %div
      = f.date_field :limit
    %div
      = f.submit 'Submit', class: 'btn-secondary'

app/views/tasks/show.html.haml
.container
  .task
    %p
      = @task.board.name
    .task_header
      %h1= @task.title
      .dropdown
        = image_tag 'Combined Shape.png', class:'dropbtn'
        .dropdown_content
          = link_to 'edit', edit_board_task_path(@task.board_id,@task.id)
          = link_to 'delete', board_task_path, data: { method: 'delete', confirm: '本当に削除してもよろしいですか'}
    .task_image
      = image_tag @task.eyecatch_image
    .task_content
      %p= @task.content
  .comment
    - @comments.each do |comment|
      %p= comment.content
    .comment_create    
      = link_to 'Add Comment', new_board_task_comment_path(@task.board_id,@task.id)
    
    
    